version: '3'

services:
  db:
    image: mysql
    container_name: crujar-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - crujar-data:/var/lib/mysql

volumes:
  crujar-data: